services:
  - type: web
    name: voting-app
    env: python
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: gunicorn mysite.wsgi:application --bind 0.0.0.0:10000
    healthCheckPath: /vote/
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,127.0.0.1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

  - type: pserv
    name: postgres-db
    env: postgresql
    plan: free
    ipAddress: private
